version: "3.7"
services:
  web:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: mongo_express_react_api
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./server:/app
    env_file:
      - .env

  mongo:
    image: mongo:4.4
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db
      # create a new user admin password and give it readWrite access to defaultDB
      - ./mongo/users.js:/docker-entrypoint-initdb.d/users.js:ro
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    # graphic interface for mongodb
    image: mongo-express
    container_name: mongo_express_gui
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  #Configure shared named volumes to be used in the services above.
  mongo-db:
