openapi: "3.0.0"
info:
  title: Mongoose Express 
  description: Mongoose Express 
  version: "0.1"
servers:
  - url: http://localhost:3003
    description: Mongoose Express 
paths:
  /status:
    get:
      operationId: checkStatus
      tags:
        - health
      description: Health endpoint
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string